url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "William Ma" # the name of your site, e.g. ACME Corp.
author:
    email: "wm274@cornell.edu"
social:
    github: "whoiswillma"
    linkedin: "william-ma-156ba4137"